/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* hier_mem_microblaze_0_local_memory_dlmb_bram_if_cntlr memory will not be tested since application resides in the same memory */
	{
		"hier_mem_mig_7series_0",
		"mig_7series",
		0x80000000,
		134217728,
	},
};

int n_memory_ranges = 1;
