# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys4DDR_Master.xdc

# Block Designs: bd/mysys/mysys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys || ORIG_REF_NAME==mysys}]

# IP: bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_microblaze_0_0 || ORIG_REF_NAME==mysys_microblaze_0_0}]

# IP: bd/mysys/ip/mysys_dlmb_v10_0/mysys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_dlmb_v10_0 || ORIG_REF_NAME==mysys_dlmb_v10_0}]

# IP: bd/mysys/ip/mysys_ilmb_v10_0/mysys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_ilmb_v10_0 || ORIG_REF_NAME==mysys_ilmb_v10_0}]

# IP: bd/mysys/ip/mysys_dlmb_bram_if_cntlr_0/mysys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mysys_dlmb_bram_if_cntlr_0}]

# IP: bd/mysys/ip/mysys_ilmb_bram_if_cntlr_0/mysys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mysys_ilmb_bram_if_cntlr_0}]

# IP: bd/mysys/ip/mysys_lmb_bram_0/mysys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_lmb_bram_0 || ORIG_REF_NAME==mysys_lmb_bram_0}]

# IP: bd/mysys/ip/mysys_microblaze_0_axi_periph_0/mysys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mysys_microblaze_0_axi_periph_0}]

# IP: bd/mysys/ip/mysys_microblaze_0_xlconcat_0/mysys_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mysys_microblaze_0_xlconcat_0}]

# IP: bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_mdm_1_0 || ORIG_REF_NAME==mysys_mdm_1_0}]

# IP: bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_clk_wiz_1_0 || ORIG_REF_NAME==mysys_clk_wiz_1_0}]

# IP: bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mysys_rst_clk_wiz_1_100M_0}]

# IP: bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_mig_7series_0_0 || ORIG_REF_NAME==mysys_mig_7series_0_0}]

# IP: bd/mysys/ip/mysys_axi_mem_intercon_0/mysys_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_mem_intercon_0 || ORIG_REF_NAME==mysys_axi_mem_intercon_0}]

# IP: bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mysys_rst_mig_7series_0_81M_0}]

# IP: bd/mysys/ip/mysys_axi_timer_0_0/mysys_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_timer_0_0 || ORIG_REF_NAME==mysys_axi_timer_0_0}]

# IP: bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_gpio_0_0 || ORIG_REF_NAME==mysys_axi_gpio_0_0}]

# IP: bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_quad_spi_0_0 || ORIG_REF_NAME==mysys_axi_quad_spi_0_0}]

# IP: bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_tft_0_0 || ORIG_REF_NAME==mysys_axi_tft_0_0}]

# IP: bd/mysys/ip/mysys_xbar_0/mysys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_xbar_0 || ORIG_REF_NAME==mysys_xbar_0}]

# IP: bd/mysys/ip/mysys_xbar_1/mysys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_xbar_1 || ORIG_REF_NAME==mysys_xbar_1}]

# IP: bd/mysys/ip/mysys_AUDIO_0_0/mysys_AUDIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_AUDIO_0_0 || ORIG_REF_NAME==mysys_AUDIO_0_0}]

# IP: bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_dma_0_0 || ORIG_REF_NAME==mysys_axi_dma_0_0}]

# IP: bd/mysys/ip/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axis_data_fifo_0_0 || ORIG_REF_NAME==mysys_axis_data_fifo_0_0}]

# IP: bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_axi_intc_0_0 || ORIG_REF_NAME==mysys_axi_intc_0_0}]

# IP: bd/mysys/ip/mysys_KEYBOARD_0_1/mysys_KEYBOARD_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_KEYBOARD_0_1 || ORIG_REF_NAME==mysys_KEYBOARD_0_1}]

# IP: bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_cc_0 || ORIG_REF_NAME==mysys_auto_cc_0}]

# IP: bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_5 || ORIG_REF_NAME==mysys_auto_us_5}]

# IP: bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_4 || ORIG_REF_NAME==mysys_auto_us_4}]

# IP: bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_3 || ORIG_REF_NAME==mysys_auto_us_3}]

# IP: bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_2 || ORIG_REF_NAME==mysys_auto_us_2}]

# IP: bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_1 || ORIG_REF_NAME==mysys_auto_us_1}]

# IP: bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_auto_us_0 || ORIG_REF_NAME==mysys_auto_us_0}]

# XDC: bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_microblaze_0_0 || ORIG_REF_NAME==mysys_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_dlmb_v10_0/mysys_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_dlmb_v10_0 || ORIG_REF_NAME==mysys_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_dlmb_v10_0/mysys_dlmb_v10_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_ilmb_v10_0/mysys_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_ilmb_v10_0 || ORIG_REF_NAME==mysys_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_ilmb_v10_0/mysys_ilmb_v10_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_dlmb_bram_if_cntlr_0/mysys_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_ilmb_bram_if_cntlr_0/mysys_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_lmb_bram_0/mysys_lmb_bram_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_mdm_1_0 || ORIG_REF_NAME==mysys_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0_ooc_trace.xdc

# XDC: bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_clk_wiz_1_0 || ORIG_REF_NAME==mysys_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_clk_wiz_1_0 || ORIG_REF_NAME==mysys_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mysys_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mysys_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0/user_design/constraints/mysys_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_mig_7series_0_0 || ORIG_REF_NAME==mysys_mig_7series_0_0}]

# XDC: bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0/user_design/constraints/mysys_mig_7series_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mysys_mig_7series_0_0 || ORIG_REF_NAME==mysys_mig_7series_0_0}]

# XDC: bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mysys_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==mysys_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_timer_0_0/mysys_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_timer_0_0 || ORIG_REF_NAME==mysys_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_timer_0_0/mysys_axi_timer_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_gpio_0_0 || ORIG_REF_NAME==mysys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_gpio_0_0 || ORIG_REF_NAME==mysys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_quad_spi_0_0 || ORIG_REF_NAME==mysys_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_quad_spi_0_0 || ORIG_REF_NAME==mysys_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_quad_spi_0_0 || ORIG_REF_NAME==mysys_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_tft_0_0 || ORIG_REF_NAME==mysys_axi_tft_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_tft_0_0 || ORIG_REF_NAME==mysys_axi_tft_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_xbar_0/mysys_xbar_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_xbar_1/mysys_xbar_1_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_dma_0_0 || ORIG_REF_NAME==mysys_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_dma_0_0 || ORIG_REF_NAME==mysys_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axis_data_fifo_0_0 || ORIG_REF_NAME==mysys_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_intc_0_0 || ORIG_REF_NAME==mysys_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_axi_intc_0_0 || ORIG_REF_NAME==mysys_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_cc_0 || ORIG_REF_NAME==mysys_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_5 || ORIG_REF_NAME==mysys_auto_us_5}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_4 || ORIG_REF_NAME==mysys_auto_us_4}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_3 || ORIG_REF_NAME==mysys_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_2 || ORIG_REF_NAME==mysys_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_1 || ORIG_REF_NAME==mysys_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1_ooc.xdc

# XDC: bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mysys_auto_us_0 || ORIG_REF_NAME==mysys_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0_ooc.xdc

# XDC: bd/mysys/mysys_ooc.xdc
