# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/game/game.cache/wt [current_project]
set_property parent.project_path E:/FPGA/game/game.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  e:/FPGA/ip_repo/KEYBOARD_1.0
  e:/FPGA/ip_repo/AUDIO_1.0
} [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  E:/FPGA/game/game.srcs/sources_1/bd/mysys/hdl/mysys_wrapper.v
  E:/FPGA/game/game.srcs/sources_1/new/microblaze_start.v
}
add_files E:/FPGA/game/game.srcs/sources_1/bd/mysys/mysys.bd
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_microblaze_0_0/mysys_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_dlmb_v10_0/mysys_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_dlmb_v10_0/mysys_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_ilmb_v10_0/mysys_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_ilmb_v10_0/mysys_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_dlmb_bram_if_cntlr_0/mysys_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_ilmb_bram_if_cntlr_0/mysys_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_lmb_bram_0/mysys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mdm_1_0/mysys_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_clk_wiz_1_0/mysys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_clk_wiz_1_100M_0/mysys_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0/user_design/constraints/mysys_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0/user_design/constraints/mysys_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_mig_7series_0_0/mysys_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_rst_mig_7series_0_81M_0/mysys_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_timer_0_0/mysys_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_timer_0_0/mysys_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_gpio_0_0/mysys_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_quad_spi_0_0/mysys_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_tft_0_0/mysys_axi_tft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_xbar_0/mysys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_xbar_1/mysys_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_dma_0_0/mysys_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0/mysys_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_axi_intc_0_0/mysys_axi_intc_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_cc_0/mysys_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_5/mysys_auto_us_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_4/mysys_auto_us_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_3/mysys_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_2/mysys_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_1/mysys_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/game/game.srcs/sources_1/bd/mysys/ip/mysys_auto_us_0/mysys_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA/game/game.srcs/sources_1/bd/mysys/mysys_ooc.xdc]
set_property is_locked true [get_files E:/FPGA/game/game.srcs/sources_1/bd/mysys/mysys.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/game/game.srcs/constrs_1/new/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/FPGA/game/game.srcs/constrs_1/new/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top microblaze_start -part xc7a100tcsg324-1


write_checkpoint -force -noxdef microblaze_start.dcp

catch { report_utilization -file microblaze_start_utilization_synth.rpt -pb microblaze_start_utilization_synth.pb }
